In [67]:
import pandas as pd
from math import pi, sqrt

# 2 - Tractament de la font de les dades

In [68]:
un_wpp24_df = pd.read_csv("../data/UN_PPP2024_Output_Births.csv")
un_wpp24_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 87 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            302 non-null    int64
 1   Variant          302 non-null    str
 2   Region           302 non-null    str
 3   Notes            79 non-null     str
 4   Location code    302 non-null    int64
 5   ISO3 Alpha-code  237 non-null    str
 6   ISO2 Alpha-code  236 non-null    str
 7   SDMX code**      283 non-null    float64
 8   Type             302 non-null    str
 9   Parent code      302 non-null    int64
 10  2024             302 non-null    str
 11  2025             302 non-null    str
 12  2026             302 non-null    str
 13  2027             302 non-null    str
 14  2028             302 non-null    str
 15  2029             302 non-null    str
 16  2030             302 non-null    str
 17  2031             302 non-null    str
 18  2032             302 non-null    str
 19  2033             302 non-null    str
 20  2034             302 non-null    str
 21  2035             302 non-null    str
 22  2036             302 non-null    str
 23  2037             302 non-null    str
 24  2038             302 non-null    str
 25  2039             302 non-null    str
 26  2040             302 non-null    str
 27  2041             302 non-null    str
 28  2042             302 non-null    str
 29  2043             302 non-null    str
 30  2044             302 non-null    str
 31  2045             302 non-null    str
 32  2046             302 non-null    str
 33  2047             302 non-null    str
 34  2048             302 non-null    str
 35  2049             302 non-null    str
 36  2050             302 non-null    str
 37  2051             302 non-null    str
 38  2052             302 non-null    str
 39  2053             302 non-null    str
 40  2054             302 non-null    str
 41  2055             302 non-null    str
 42  2056             302 non-null    str
 43  2057             302 non-null    str
 44  2058             302 non-null    str
 45  2059             302 non-null    str
 46  2060             302 non-null    str
 47  2061             302 non-null    str
 48  2062             302 non-null    str
 49  2063             302 non-null    str
 50  2064             302 non-null    str
 51  2065             302 non-null    str
 52  2066             302 non-null    str
 53  2067             302 non-null    str
 54  2068             302 non-null    str
 55  2069             302 non-null    str
 56  2070             302 non-null    str
 57  2071             302 non-null    str
 58  2072             302 non-null    str
 59  2073             302 non-null    str
 60  2074             302 non-null    str
 61  2075             302 non-null    str
 62  2076             302 non-null    str
 63  2077             302 non-null    str
 64  2078             302 non-null    str
 65  2079             302 non-null    str
 66  2080             302 non-null    str
 67  2081             302 non-null    str
 68  2082             302 non-null    str
 69  2083             302 non-null    str
 70  2084             302 non-null    str
 71  2085             302 non-null    str
 72  2086             302 non-null    str
 73  2087             302 non-null    str
 74  2088             302 non-null    str
 75  2089             302 non-null    str
 76  2090             302 non-null    str
 77  2091             302 non-null    str
 78  2092             302 non-null    str
 79  2093             302 non-null    str
 80  2094             302 non-null    str
 81  2095             302 non-null    str
 82  2096             302 non-null    str
 83  2097             302 non-null    str
 84  2098             302 non-null    str
 85  2099             302 non-null    str
 86  2100             302 non-null    str
dtypes: float64(1), int64(3), str(83)
memory usage: 344.4 KB

In [69]:
un_wpp24_df = un_wpp24_df.drop(["Index","Variant","Notes","ISO3 Alpha-code","ISO2 Alpha-code","SDMX code**"], axis=1)
un_wpp24_df.info()
un_wpp24_df

<class 'pandas.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Region         302 non-null    str
 1   Location code  302 non-null    int64
 2   Type           302 non-null    str
 3   Parent code    302 non-null    int64
 4   2024           302 non-null    str
 5   2025           302 non-null    str
 6   2026           302 non-null    str
 7   2027           302 non-null    str
 8   2028           302 non-null    str
 9   2029           302 non-null    str
 10  2030           302 non-null    str
 11  2031           302 non-null    str
 12  2032           302 non-null    str
 13  2033           302 non-null    str
 14  2034           302 non-null    str
 15  2035           302 non-null    str
 16  2036           302 non-null    str
 17  2037           302 non-null    str
 18  2038           302 non-null    str
 19  2039           302 non-null    str
 20  2040           302 non-null    str
 21  2041           302 non-null    str
 22  2042           302 non-null    str
 23  2043           302 non-null    str
 24  2044           302 non-null    str
 25  2045           302 non-null    str
 26  2046           302 non-null    str
 27  2047           302 non-null    str
 28  2048           302 non-null    str
 29  2049           302 non-null    str
 30  2050           302 non-null    str
 31  2051           302 non-null    str
 32  2052           302 non-null    str
 33  2053           302 non-null    str
 34  2054           302 non-null    str
 35  2055           302 non-null    str
 36  2056           302 non-null    str
 37  2057           302 non-null    str
 38  2058           302 non-null    str
 39  2059           302 non-null    str
 40  2060           302 non-null    str
 41  2061           302 non-null    str
 42  2062           302 non-null    str
 43  2063           302 non-null    str
 44  2064           302 non-null    str
 45  2065           302 non-null    str
 46  2066           302 non-null    str
 47  2067           302 non-null    str
 48  2068           302 non-null    str
 49  2069           302 non-null    str
 50  2070           302 non-null    str
 51  2071           302 non-null    str
 52  2072           302 non-null    str
 53  2073           302 non-null    str
 54  2074           302 non-null    str
 55  2075           302 non-null    str
 56  2076           302 non-null    str
 57  2077           302 non-null    str
 58  2078           302 non-null    str
 59  2079           302 non-null    str
 60  2080           302 non-null    str
 61  2081           302 non-null    str
 62  2082           302 non-null    str
 63  2083           302 non-null    str
 64  2084           302 non-null    str
 65  2085           302 non-null    str
 66  2086           302 non-null    str
 67  2087           302 non-null    str
 68  2088           302 non-null    str
 69  2089           302 non-null    str
 70  2090           302 non-null    str
 71  2091           302 non-null    str
 72  2092           302 non-null    str
 73  2093           302 non-null    str
 74  2094           302 non-null    str
 75  2095           302 non-null    str
 76  2096           302 non-null    str
 77  2097           302 non-null    str
 78  2098           302 non-null    str
 79  2099           302 non-null    str
 80  2100           302 non-null    str
dtypes: int64(2), str(79)
memory usage: 326.2 KB

,Region,Location code,Type,Parent code,2024,2025,2026,2027,2028,2029,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,World,900,World,0,132 406,132 399,132 503,132 591,132 761,132 989,...,114 283,113 773,113 262,112 773,112 282,111 831,111 397,110 941,110 501,110 028
1,Sustainable Development Goal (SDG) regions,1828,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,Sub-Saharan Africa,1834,SDG region,1828,40 718,41 210,41 678,42 122,42 590,43 052,...,48 915,48 772,48 642,48 515,48 372,48 227,48 079,47 931,47 766,47 608
3,Northern Africa and Western Asia,1833,SDG region,1828,11 822,11 834,11 881,11 927,11 963,12 004,...,11 275,11 238,11 199,11 156,11 109,11 070,11 032,10 997,10 961,10 925
4,Central and Southern Asia,1831,SDG region,1828,38 993,38 815,38 672,38 527,38 391,38 287,...,27 629,27 463,27 273,27 088,26 901,26 736,26 570,26 383,26 217,26 028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,Samoa,882,Country/Area,957,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
298,Tokelau,772,Country/Area,957,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
299,Tonga,776,Country/Area,957,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
300,Tuvalu,798,Country/Area,957,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
301,Wallis and Futuna Islands,876,Country/Area,957,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
for i in range(2100 - 2024 + 1):
    un_wpp24_df[f"{2024 + i}"] = un_wpp24_df[un_wpp24_df[f"{2024 + i}"] != "..."][f"{2024 + i}"].apply(lambda x: int(x.replace(" ", "")))

un_wpp24_df

,Region,Location code,Type,Parent code,2024,2025,2026,2027,2028,2029,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,World,900,World,0,132406.0,132399.0,132503.0,132591.0,132761.0,132989.0,...,114283.0,113773.0,113262.0,112773.0,112282.0,111831.0,111397.0,110941.0,110501.0,110028.0
1,Sustainable Development Goal (SDG) regions,1828,Label/Separator,900,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sub-Saharan Africa,1834,SDG region,1828,40718.0,41210.0,41678.0,42122.0,42590.0,43052.0,...,48915.0,48772.0,48642.0,48515.0,48372.0,48227.0,48079.0,47931.0,47766.0,47608.0
3,Northern Africa and Western Asia,1833,SDG region,1828,11822.0,11834.0,11881.0,11927.0,11963.0,12004.0,...,11275.0,11238.0,11199.0,11156.0,11109.0,11070.0,11032.0,10997.0,10961.0,10925.0
4,Central and Southern Asia,1831,SDG region,1828,38993.0,38815.0,38672.0,38527.0,38391.0,38287.0,...,27629.0,27463.0,27273.0,27088.0,26901.0,26736.0,26570.0,26383.0,26217.0,26028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,Samoa,882,Country/Area,957,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
298,Tokelau,772,Country/Area,957,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299,Tonga,776,Country/Area,957,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
300,Tuvalu,798,Country/Area,957,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301,Wallis and Futuna Islands,876,Country/Area,957,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
region_df = un_wpp24_df[un_wpp24_df["Type"] == "Region"]
region_df

,Region,Location code,Type,Parent code,2024,2025,2026,2027,2028,2029,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
37,Africa,903,Region,1840,46621.0,47080.0,47562.0,48018.0,48489.0,48964.0,...,54374.0,54207.0,54050.0,53894.0,53719.0,53548.0,53375.0,53206.0,53018.0,52837.0
101,Asia,935,Region,1840,65492.0,65165.0,64911.0,64652.0,64433.0,64252.0,...,44331.0,44044.0,43747.0,43465.0,43193.0,42953.0,42725.0,42477.0,42255.0,42001.0
158,Europe,908,Region,1840,6273.0,6207.0,6141.0,6089.0,6050.0,6019.0,...,5038.0,5013.0,4992.0,4976.0,4964.0,4954.0,4948.0,4946.0,4943.0,4943.0
213,Americas,5505,Region,1840,13315.0,13244.0,13185.0,13139.0,13088.0,13073.0,...,9877.0,9852.0,9802.0,9786.0,9757.0,9734.0,9715.0,9673.0,9652.0,9640.0
214,Latin America and the Caribbean,904,Region,1840,9308.0,9227.0,9160.0,9099.0,9043.0,8995.0,...,5498.0,5455.0,5413.0,5369.0,5327.0,5286.0,5246.0,5206.0,5169.0,5131.0
268,Northern America,905,Region,1840,4017.0,4026.0,4036.0,4040.0,4054.0,4069.0,...,4289.0,4301.0,4308.0,4315.0,4328.0,4337.0,4351.0,4355.0,4366.0,4367.0
274,Oceania,909,Region,1840,695.0,694.0,693.0,692.0,692.0,690.0,...,752.0,752.0,753.0,753.0,752.0,752.0,752.0,752.0,751.0,750.0

In [72]:
source_df = region_df[["Region", "Location code"]]
source_df

                              Region  Location code
37                            Africa            903
101                             Asia            935
158                           Europe            908
213                         Americas           5505
214  Latin America and the Caribbean            904
268                 Northern America            905
274                          Oceania            909

In [73]:
source_df = source_df[source_df["Region"] != "Americas"]

# 3 - Unió de datasets (àrea bombolles + font oficial)

In [74]:
change_name = {
    214: "Latam & Caribbean",
    268: "North America"
               }

for k, v in change_name.items():
    source_df.loc[k, "Region"] = v

In [75]:
source_df.rename({"Region": "Continent"}, inplace=True, axis=1)

In [76]:
source_df

             Continent  Location code
37              Africa            903
101               Asia            935
158             Europe            908
214  Latam & Caribbean            904
268      North America            905
274            Oceania            909

In [77]:
for col in source_df.columns:
    if col != "Continent":
        source_df[col] = source_df[col].astype(int)

In [78]:
subregion_df = un_wpp24_df[un_wpp24_df["Type"] == "Subregion"]
subregion_df = subregion_df[["Location code", "Parent code"]]
subregion_df

     Location code  Parent code
38             910          903
59             911          903
69             912          903
77             913          903
83             914          903
102           5500          935
108            906          935
117           5501          935
127            920          935
139            922          935
159            923          908
170            924          908
185            925          908
203            926          908
215            915          904
244            916          904
253            931          904
275            927          909
278            928          909
284            954          909
292            957          909

In [79]:
subregion_df.loc[len(subregion_df)] = [905, 905]
subregion_df

     Location code  Parent code
38             910          903
59             911          903
69             912          903
77             913          903
83             914          903
102           5500          935
108            906          935
117           5501          935
127            920          935
139            922          935
159            923          908
170            924          908
185            925          908
203            926          908
215            915          904
244            916          904
253            931          904
275            927          909
278            928          909
284            954          909
292            957          909
21             905          905

In [80]:
countries_df = un_wpp24_df[un_wpp24_df["Type"] == "Country/Area"]
countries_df = countries_df.drop(["Location code", "Type"], axis=1)
countries_df

,Region,Parent code,2024,2025,2026,2027,2028,2029,2030,2031,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
39,Burundi,910,467.0,469.0,472.0,476.0,483.0,491.0,501.0,509.0,...,561.0,560.0,559.0,557.0,556.0,555.0,555.0,554.0,552.0,551.0
40,Comoros,910,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,...,26.0,26.0,26.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
41,Djibouti,910,24.0,24.0,24.0,25.0,25.0,25.0,25.0,25.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,21.0
42,Eritrea,910,102.0,103.0,105.0,107.0,109.0,111.0,112.0,113.0,...,110.0,109.0,109.0,108.0,108.0,107.0,106.0,106.0,105.0,105.0
43,Ethiopia,910,4156.0,4177.0,4213.0,4246.0,4275.0,4303.0,4326.0,4344.0,...,4734.0,4724.0,4713.0,4700.0,4691.0,4680.0,4668.0,4657.0,4648.0,4633.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,Samoa,957,5.0,5.0,5.0,5.0,5.0,5.0,6.0,6.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
298,Tokelau,957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299,Tonga,957,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
300,Tuvalu,957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301,Wallis and Futuna Islands,957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [81]:
countries_df[countries_df["Region"] == "Canada"]

,Region,Parent code,2024,2025,2026,2027,2028,2029,2030,2031,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
270,Canada,905,361.0,361.0,361.0,361.0,363.0,363.0,364.0,365.0,...,436.0,438.0,440.0,442.0,443.0,445.0,447.0,449.0,451.0,452.0

In [82]:
subregion_df = subregion_df.rename({"Parent code": "Continent code"}, axis=1)
merge_df = subregion_df.merge(countries_df, left_on="Location code", right_on="Parent code")
merge_df = merge_df.drop(["Location code", "Parent code"], axis=1)
merge_df

,Continent code,Region,2024,2025,2026,2027,2028,2029,2030,2031,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,903,Burundi,467.0,469.0,472.0,476.0,483.0,491.0,501.0,509.0,...,561.0,560.0,559.0,557.0,556.0,555.0,555.0,554.0,552.0,551.0
1,903,Comoros,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,...,26.0,26.0,26.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
2,903,Djibouti,24.0,24.0,24.0,25.0,25.0,25.0,25.0,25.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,21.0
3,903,Eritrea,102.0,103.0,105.0,107.0,109.0,111.0,112.0,113.0,...,110.0,109.0,109.0,108.0,108.0,107.0,106.0,106.0,105.0,105.0
4,903,Ethiopia,4156.0,4177.0,4213.0,4246.0,4275.0,4303.0,4326.0,4344.0,...,4734.0,4724.0,4713.0,4700.0,4691.0,4680.0,4668.0,4657.0,4648.0,4633.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,905,Bermuda,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
233,905,Canada,361.0,361.0,361.0,361.0,363.0,363.0,364.0,365.0,...,436.0,438.0,440.0,442.0,443.0,445.0,447.0,449.0,451.0,452.0
234,905,Greenland,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
235,905,Saint Pierre and Miquelon,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236,905,United States of America,3654.0,3664.0,3673.0,3677.0,3690.0,3705.0,3722.0,3738.0,...,3853.0,3862.0,3867.0,3873.0,3884.0,3891.0,3903.0,3905.0,3914.0,3914.0

In [83]:
merge_df[merge_df["Region"] == "Canada"]

,Continent code,Region,2024,2025,2026,2027,2028,2029,2030,2031,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
233,905,Canada,361.0,361.0,361.0,361.0,363.0,363.0,364.0,365.0,...,436.0,438.0,440.0,442.0,443.0,445.0,447.0,449.0,451.0,452.0

In [84]:
final_df = merge_df.merge(source_df, left_on="Continent code", right_on="Location code")
final_df = final_df.drop(["Continent code", "Location code"], axis=1)
final_df

,Region,2024,2025,2026,2027,2028,2029,2030,2031,2032,...,2092,2093,2094,2095,2096,2097,2098,2099,2100,Continent
0,Burundi,467.0,469.0,472.0,476.0,483.0,491.0,501.0,509.0,519.0,...,560.0,559.0,557.0,556.0,555.0,555.0,554.0,552.0,551.0,Africa
1,Comoros,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,...,26.0,26.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,Africa
2,Djibouti,24.0,24.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,21.0,Africa
3,Eritrea,102.0,103.0,105.0,107.0,109.0,111.0,112.0,113.0,114.0,...,109.0,109.0,108.0,108.0,107.0,106.0,106.0,105.0,105.0,Africa
4,Ethiopia,4156.0,4177.0,4213.0,4246.0,4275.0,4303.0,4326.0,4344.0,4361.0,...,4724.0,4713.0,4700.0,4691.0,4680.0,4668.0,4657.0,4648.0,4633.0,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Bermuda,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,North America
233,Canada,361.0,361.0,361.0,361.0,363.0,363.0,364.0,365.0,366.0,...,438.0,440.0,442.0,443.0,445.0,447.0,449.0,451.0,452.0,North America
234,Greenland,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,North America
235,Saint Pierre and Miquelon,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,North America
236,United States of America,3654.0,3664.0,3673.0,3677.0,3690.0,3705.0,3722.0,3738.0,3759.0,...,3862.0,3867.0,3873.0,3884.0,3891.0,3903.0,3905.0,3914.0,3914.0,North America

In [85]:
final_df["Continent"].drop_duplicates()

0                 Africa
58                  Asia
109               Europe
159    Latam & Caribbean
209              Oceania
232        North America
Name: Continent, dtype: str

In [87]:
for col in final_df.columns:
    if col != "Region" and col != "Continent":
        final_df[col] = final_df[col].astype(int)

In [88]:
final_df.to_csv("../data/global_births_countries.csv", index=False)